<?php
/**
 * The Abrahamic Archive — configuration and the whole data layer.
 *
 * There is no framework and no dependency here. The reading texts are flat
 * JSON files under ../corpus, one per chapter, and the search index is a
 * SQLite database read through pdo_sqlite. Both sit outside the document
 * root, so nothing can be fetched except through these pages.
 */
declare(strict_types=1);

const APP_NAME    = 'The Abrahamic Archive';
const APP_TAGLINE = 'Judaism, Christianity and Islam in modern English';

/* The colours a reader can mark a verse with. Named rather than numbered so
   that a saved highlight survives a change to the palette, and so that the
   export a reader takes away says `amber` rather than `#f0c674`. */
/**
 * The reading plans, generated by `tools.build_plans` and checked against the
 * corpus when they are written, so a plan can never point at a chapter that
 * is not there.
 */
function plans(): array
{
    static $cache = null;
    if ($cache === null) {
        $raw = @file_get_contents(__DIR__ . '/../data/plans.json');
        $d = $raw ? json_decode($raw, true) : null;
        $cache = is_array($d) && isset($d['plans']) ? $d['plans'] : [];
    }
    return $cache;
}

/* Words too ordinary to be worth a footnote, however many Hebrew words hide
   behind them. Kept short on purpose: `light`, `word` and `fear` all belong
   in a footnote, and the point of the feature is that they do. */
const FOOTNOTE_SKIP = [
    'that', 'this', 'they', 'them', 'their', 'there', 'then', 'when', 'were',
    'have', 'hath', 'with', 'from', 'unto', 'shall', 'which', 'said', 'come',
    'came', 'went', 'made', 'make', 'thou', 'thee', 'your', 'you', 'his',
    'her', 'him', 'and', 'the', 'for', 'but', 'not', 'all', 'was', 'are',
    'one', 'two', 'out', 'let', 'set', 'put', 'took', 'take', 'give', 'given',
    'also', 'after', 'before', 'because', 'these', 'those', 'upon', 'into',
    'thing', 'things', 'man', 'men', 'people', 'day', 'days', 'time',
    /* A second class, learned by running it over Genesis 1: words that come
       back with a hundred originals behind them and tell a reader nothing,
       because the many originals are an artefact of how often the word is
       needed rather than of any depth in it. */
    'place', 'together', 'great', 'over', 'very', 'own', 'will', 'more',
    'every', 'other', 'same', 'such', 'some', 'like', 'well', 'much',
    'many', 'good', 'against', 'about', 'down', 'again', 'away', 'back',
    'through', 'under', 'between', 'among', 'where', 'while', 'until',
    'himself', 'themselves', 'whosoever', 'whatsoever', 'therefore',
    'behold', 'saying', 'called', 'know', 'knew', 'become', 'came',
];

/**
 * Which words in a chapter are hiding more than one word underneath.
 *
 * Without a Strong's-tagged text there is no telling *which* Hebrew word a
 * given `light` translates. What can be said, and is worth saying, is that
 * the King James translators used the word `light` for thirty-four different
 * ones — so the reader knows there is a question here even though this
 * archive cannot answer it for this verse. The footnote says exactly that
 * much and no more.
 *
 * -> ['light' => ['n' => 34, 'top' => [entry, …]], …], the richest first.
 */
function footnote_words(string $text, int $limit = 10, int $least = 4): array
{
    $db = strongs_db();
    if (!$db) {
        return [];
    }
    preg_match_all('/[A-Za-z]{3,}/', $text, $m);
    $seen = array_unique(array_map('strtolower', $m[0]));
    $seen = array_diff($seen, FOOTNOTE_SKIP);
    if (!$seen) {
        return [];
    }

    /* One query for the whole chapter rather than one per word. */
    $in = implode(',', array_fill(0, count($seen), '?'));
    /* The two numbers are cast and interpolated rather than bound: PDO's
       SQLite driver binds every parameter as text, and `HAVING n >= '4'`
       compares an integer against a string and matches nothing at all. */
    $least = max(2, (int) $least);
    $limit = max(1, min(40, (int) $limit));
    $q = $db->prepare(
        "SELECT x.word, COUNT(DISTINCT x.id) AS n
           FROM english x WHERE x.word IN ($in)
          GROUP BY x.word HAVING n >= $least
          ORDER BY n DESC, x.word LIMIT $limit");
    if (!$q || !$q->execute(array_values($seen))) {
        return [];
    }

    $out = [];
    foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $e = $db->prepare(
            /* Two signals, in order. First: does the entry lead with this
               sense? Strong lists renderings commonest-first, so a word in
               the first three is what the entry mostly means. Then, among
               those, how many other entries are derived from it — the root
               of a family is the word a reader wants, and the one that
               position alone will never surface. */
            'SELECT e.id, e.lang, e.word, e.sense FROM english x
               JOIN entry e ON e.id = x.id
              WHERE x.word = ?
              ORDER BY (x.rank <= 2) DESC, e.refs DESC, x.rank LIMIT 4');
        $top = ($e && $e->execute([$row['word']])) ? $e->fetchAll(PDO::FETCH_ASSOC) : [];
        if ($top) {
            $out[$row['word']] = ['n' => (int) $row['n'], 'top' => $top];
        }
    }
    return $out;
}

/**
 * Put the footnote markers into a run of already-escaped text.
 *
 * The text is escaped before this sees it, and the footnoted words are plain
 * letters with no entity to collide with, so a word-boundary substitution on
 * the escaped string is safe. `$used` carries across the whole chapter: a
 * word is marked the first time it appears and left alone after that, which
 * is what a footnote in a book does.
 */
function mark_footnotes(string $escaped, array $words, array &$used): string
{
    if (!$words) {
        return $escaped;
    }
    /* Numbered in the order they are met on the page, not in the order the
       lexicon happened to return them, so a reader following the numbers
       down a verse finds them going up. */
    $pending = [];
    foreach ($words as $word => $_d) {
        if (isset($used[$word])) {
            continue;
        }
        $at = stripos($escaped, $word);
        if ($at !== false) {
            $pending[$word] = $at;
        }
    }
    asort($pending);

    foreach ($pending as $word => $_at) {
        $n = count($used) + 1;
        $out = preg_replace_callback(
            '/\b(' . preg_quote($word, '/') . ')\b/i',
            function ($m) use ($word, $n) {
                return '<span class="fnw">' . $m[1] . '</span>'
                     . '<a class="fnm" id="fnr-' . $word . '" href="#fn-' . $word
                     . '" title="Behind this word in the Hebrew and Greek">'
                     . $n . '</a>';
            },
            $escaped, 1, $count);
        if ($count) {
            $used[$word] = $n;
            $escaped = $out;
        }
    }
    return $escaped;
}

/** Strong's dictionaries, if `tools.ingest_strongs` has been run. */
function strongs_db(): ?PDO
{
    static $db = false;
    if ($db === false) {
        $path = CORPUS_DIR . '/strongs.sqlite';
        try {
            $db = is_readable($path)
                ? new PDO('sqlite:' . $path, null, null,
                          [PDO::ATTR_ERRMODE => PDO::ERRMODE_SILENT])
                : null;
        } catch (Throwable $e) {
            $db = null;
        }
    }
    return $db;
}

function strongs_entry(string $id): array
{
    $db = strongs_db();
    if (!$db) {
        return [];
    }
    $q = $db->prepare('SELECT * FROM entry WHERE id = ?');
    return ($q && $q->execute([$id])) ? $q->fetchAll(PDO::FETCH_ASSOC) : [];
}

/** Every Hebrew and Greek word the King James rendered by one English word. */
function strongs_by_english(string $word): array
{
    $db = strongs_db();
    if (!$db) {
        return [];
    }
    $q = $db->prepare(
        'SELECT e.* FROM english x JOIN entry e ON e.id = x.id
          WHERE x.word = ? ORDER BY e.lang DESC, e.num LIMIT 40');
    return ($q && $q->execute([$word])) ? $q->fetchAll(PDO::FETCH_ASSOC) : [];
}

function strongs_by_word(string $word): array
{
    $db = strongs_db();
    if (!$db) {
        return [];
    }
    $q = $db->prepare(
        'SELECT * FROM entry WHERE word = ? OR word LIKE ? ORDER BY num LIMIT 40');
    return ($q && $q->execute([$word, $word . '%'])) ? $q->fetchAll(PDO::FETCH_ASSOC) : [];
}

/**
 * The citation index — who quotes what.
 *
 * Built by `tools.build_links` from the way the sources cite each other in
 * their own text: `Gen. i. 1`, `Matt. 5:9`, `Sura ii. 255`. A citation is
 * filed against a canonical reference rather than a translation, so a
 * reference made in a Catholic commentary finds the same verse in the Jewish
 * Publication Society's translation of it.
 *
 * The index is optional. Where it has not been built the reader loses a
 * feature and nothing else, so every function here returns empty rather than
 * failing.
 */
function links_db(): ?PDO
{
    static $db = false;
    if ($db === false) {
        $path = CORPUS_DIR . '/links.sqlite';
        try {
            $db = is_readable($path)
                ? new PDO('sqlite:' . $path, null, null,
                          [PDO::ATTR_ERRMODE => PDO::ERRMODE_SILENT])
                : null;
        } catch (Throwable $e) {
            $db = null;
        }
    }
    return $db;
}

/** The canonical book a work is an edition of, or null. */
function canon_book(string $workId): ?array
{
    $db = links_db();
    if (!$db) {
        return null;
    }
    $q = $db->prepare('SELECT key, label FROM book WHERE work = ?');
    if (!$q || !$q->execute([$workId])) {
        return null;
    }
    $row = $q->fetch(PDO::FETCH_ASSOC);
    return $row ?: null;
}

/** How many works cite each verse of one chapter: ['14' => 41, …]. */
function citation_counts(string $bookKey, string $chapter): array
{
    $db = links_db();
    if (!$db) {
        return [];
    }
    $q = $db->prepare(
        'SELECT target, works FROM total WHERE target LIKE ?');
    if (!$q || !$q->execute([$bookKey . '|' . $chapter . '|%'])) {
        return [];
    }
    $out = [];
    foreach ($q->fetchAll(PDO::FETCH_ASSOC) as $r) {
        $bits = explode('|', $r['target']);
        if (count($bits) === 3 && $bits[1] === $chapter) {
            $out[$bits[2]] = (int) $r['works'];
        }
    }
    return $out;
}

/** The works that cite one verse, the heaviest citers first. */
function cited_by(string $target, int $limit = 300): array
{
    $db = links_db();
    if (!$db) {
        return [];
    }
    $q = $db->prepare(
        'SELECT work, title, religion, section, n FROM cite
          WHERE target = ? ORDER BY n DESC, title LIMIT ?');
    if (!$q || !$q->execute([$target, $limit])) {
        return [];
    }
    return $q->fetchAll(PDO::FETCH_ASSOC);
}

/**
 * The verse for today. Chosen by the date rather than at random, so that
 * everyone who opens the archive on the same day meets the same verse and a
 * reload does not shuffle it.
 */
function verse_of_the_day(): ?array
{
    $raw = @file_get_contents(__DIR__ . '/../data/daily.json');
    $d = $raw ? json_decode($raw, true) : null;
    $all = is_array($d) && !empty($d['verses']) ? $d['verses'] : [];
    if (!$all) {
        return null;
    }
    $day = (int) floor(time() / 86400);
    return $all[$day % count($all)];
}

function plan(string $id): ?array
{
    foreach (plans() as $p) {
        if ($p['id'] === $id) {
            return $p;
        }
    }
    return null;
}

/* FTS5 marks a match with whatever two strings it is given. Real tags cannot
   be used: the snippet is escaped as ordinary text afterwards, and an escaped
   <mark> is just an angle bracket on the page. So two control characters
   stand in, survive escaping untouched, and become the tags at the very end.
   They cannot occur in the corpus, which is what makes the swap safe. */
const HI = "\x02";
const HO = "\x03";

const HIGHLIGHTS = [
    'amber'  => 'Amber',
    'rose'   => 'Rose',
    'sage'   => 'Sage',
    'sky'    => 'Sky',
    'violet' => 'Violet',
];

define('CORPUS_DIR', dirname(__DIR__, 2) . '/corpus');
define('WORKS_DIR',  CORPUS_DIR . '/works');
define('SEARCH_DB',  CORPUS_DIR . '/search.sqlite');

/** Read a JSON file, or null. */
function json_file(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $raw = file_get_contents($path);
    if ($raw === false) {
        return null;
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : null;
}

/** The catalog, read once per request. */
function catalog(): array
{
    static $cat = null;
    if ($cat === null) {
        $cat = json_file(CORPUS_DIR . '/catalog.json') ?? [
            'religions' => [], 'totals' => [], 'name' => APP_NAME,
        ];
    }
    return $cat;
}

/** One religion's block of the catalog, or null. */
function religion(string $id): ?array
{
    foreach (catalog()['religions'] as $r) {
        if ($r['id'] === $id) {
            return $r;
        }
    }
    return null;
}

/**
 * Where a work lives. Work ids come from the URL, so the id is checked
 * against a strict pattern and the religion against the known list before
 * either reaches the filesystem.
 */
function work_dir(string $workId): ?string
{
    if (!preg_match('/^[a-z0-9][a-z0-9\-]{0,79}$/', $workId)) {
        return null;
    }
    foreach (['judaism', 'christianity', 'islam'] as $religion) {
        $dir = WORKS_DIR . '/' . $religion . '/' . $workId;
        if (is_file($dir . '/work.json')) {
            return $dir;
        }
    }
    return null;
}

/** A work's metadata, or null. */
function work(string $workId): ?array
{
    static $cache = [];
    if (array_key_exists($workId, $cache)) {
        return $cache[$workId];
    }
    $dir = work_dir($workId);
    return $cache[$workId] = $dir ? json_file($dir . '/work.json') : null;
}

/** One chapter of a work, or null. */
function chapter(string $workId, string $n): ?array
{
    if (!preg_match('/^[0-9]{1,4}[a-z]?$/i', $n)) {
        return null;
    }
    $dir = work_dir($workId);
    return $dir ? json_file($dir . '/c/' . $n . '.json') : null;
}

/** The chapter before and after this one, for the reader's footer. */
function neighbours(array $meta, string $n): array
{
    $list = array_column($meta['chapters'] ?? [], 'n');
    $i = array_search($n, $list, true);
    if ($i === false) {
        return [null, null];
    }
    return [$list[$i - 1] ?? null, $list[$i + 1] ?? null];
}

/**
 * Other editions of the same work — the four Qur'ans, or the Hebrew
 * scriptures in their Jewish and Christian translations. Matched on title,
 * which is what makes two entries the same book in different hands.
 */
function editions_of(array $meta): array
{
    $out = [];
    foreach (catalog()['religions'] as $r) {
        foreach ($r['sections'] as $s) {
            foreach ($s['works'] as $w) {
                if ($w['id'] === $meta['id'] || !empty($w['borrowed_from'])) {
                    continue;
                }
                if (mb_strtolower($w['title']) === mb_strtolower($meta['title'])) {
                    $out[] = $w;
                }
            }
        }
    }
    return $out;
}

/** Open the search index, or null when it has not been built. */
function search_db(): ?PDO
{
    static $db = false;
    if ($db !== false) {
        return $db;
    }
    if (!is_file(SEARCH_DB) || !extension_loaded('pdo_sqlite')) {
        return $db = null;
    }
    try {
        $db = new PDO('sqlite:' . SEARCH_DB, null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        $db->exec('PRAGMA query_only = 1');
    } catch (PDOException) {
        $db = null;
    }
    return $db;
}

/**
 * Turn what someone typed into an FTS5 query.
 *
 * FTS5's own syntax uses ", *, NEAR, AND and so on, and a stray quote is a
 * syntax error rather than a search. Words are extracted and re-quoted, so
 * anything at all can be typed safely; a "phrase in quotes" is kept as one.
 */
function fts_query(string $q): string
{
    $terms = [];
    if (preg_match_all('/"([^"]+)"/u', $q, $m)) {
        foreach ($m[1] as $phrase) {
            $words = preg_split('/[^\p{L}\p{N}]+/u', $phrase, -1, PREG_SPLIT_NO_EMPTY);
            if ($words) {
                $terms[] = '"' . implode(' ', $words) . '"';
            }
        }
        $q = preg_replace('/"[^"]+"/u', ' ', $q);
    }
    foreach (preg_split('/[^\p{L}\p{N}\*]+/u', $q, -1, PREG_SPLIT_NO_EMPTY) as $w) {
        $star = str_ends_with($w, '*');
        $w = trim($w, '*');
        if ($w === '') {
            continue;
        }
        $terms[] = '"' . $w . '"' . ($star ? '*' : '');
    }
    return implode(' ', $terms);
}

/** Escape for HTML. */
function e(?string $s): string
{
    return htmlspecialchars((string) $s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/** A URL within the app. */
function u(string $page, array $params = []): string
{
    return $params ? $page . '?' . http_build_query($params) : $page;
}

function religion_name(string $id): string
{
    return ['judaism' => 'Judaism', 'christianity' => 'Christianity',
            'islam' => 'Islam'][$id] ?? $id;
}

/** How a work was modernized, in words. */
function tier_label(?string $tier): string
{
    return match ($tier) {
        'full' => 'Modernized in full',
        'safe' => 'Lightly modernized',
        'none' => 'As received',
        default => 'Modernized',
    };
}

function num(int|float|null $n): string
{
    return number_format((float) ($n ?? 0));
}
