<?php
/**
 * The Abrahamic Archive — configuration and the whole data layer.
 *
 * There is no framework and no dependency here. The reading texts are flat
 * JSON files under ../corpus, one per chapter, and the search index is a
 * SQLite database read through pdo_sqlite. Both sit outside the document
 * root, so nothing can be fetched except through these pages.
 */
declare(strict_types=1);

const APP_NAME    = 'The Abrahamic Archive';
const APP_TAGLINE = 'Judaism, Christianity and Islam in modern English';

/* The colours a reader can mark a verse with. Named rather than numbered so
   that a saved highlight survives a change to the palette, and so that the
   export a reader takes away says `amber` rather than `#f0c674`. */
/**
 * The reading plans, generated by `tools.build_plans` and checked against the
 * corpus when they are written, so a plan can never point at a chapter that
 * is not there.
 */
function plans(): array
{
    static $cache = null;
    if ($cache === null) {
        $raw = @file_get_contents(__DIR__ . '/../data/plans.json');
        $d = $raw ? json_decode($raw, true) : null;
        $cache = is_array($d) && isset($d['plans']) ? $d['plans'] : [];
    }
    return $cache;
}

/**
 * The verse for today. Chosen by the date rather than at random, so that
 * everyone who opens the archive on the same day meets the same verse and a
 * reload does not shuffle it.
 */
function verse_of_the_day(): ?array
{
    $raw = @file_get_contents(__DIR__ . '/../data/daily.json');
    $d = $raw ? json_decode($raw, true) : null;
    $all = is_array($d) && !empty($d['verses']) ? $d['verses'] : [];
    if (!$all) {
        return null;
    }
    $day = (int) floor(time() / 86400);
    return $all[$day % count($all)];
}

function plan(string $id): ?array
{
    foreach (plans() as $p) {
        if ($p['id'] === $id) {
            return $p;
        }
    }
    return null;
}

const HIGHLIGHTS = [
    'amber'  => 'Amber',
    'rose'   => 'Rose',
    'sage'   => 'Sage',
    'sky'    => 'Sky',
    'violet' => 'Violet',
];

define('CORPUS_DIR', dirname(__DIR__, 2) . '/corpus');
define('WORKS_DIR',  CORPUS_DIR . '/works');
define('SEARCH_DB',  CORPUS_DIR . '/search.sqlite');

/** Read a JSON file, or null. */
function json_file(string $path): ?array
{
    if (!is_file($path)) {
        return null;
    }
    $raw = file_get_contents($path);
    if ($raw === false) {
        return null;
    }
    $data = json_decode($raw, true);
    return is_array($data) ? $data : null;
}

/** The catalog, read once per request. */
function catalog(): array
{
    static $cat = null;
    if ($cat === null) {
        $cat = json_file(CORPUS_DIR . '/catalog.json') ?? [
            'religions' => [], 'totals' => [], 'name' => APP_NAME,
        ];
    }
    return $cat;
}

/** One religion's block of the catalog, or null. */
function religion(string $id): ?array
{
    foreach (catalog()['religions'] as $r) {
        if ($r['id'] === $id) {
            return $r;
        }
    }
    return null;
}

/**
 * Where a work lives. Work ids come from the URL, so the id is checked
 * against a strict pattern and the religion against the known list before
 * either reaches the filesystem.
 */
function work_dir(string $workId): ?string
{
    if (!preg_match('/^[a-z0-9][a-z0-9\-]{0,79}$/', $workId)) {
        return null;
    }
    foreach (['judaism', 'christianity', 'islam'] as $religion) {
        $dir = WORKS_DIR . '/' . $religion . '/' . $workId;
        if (is_file($dir . '/work.json')) {
            return $dir;
        }
    }
    return null;
}

/** A work's metadata, or null. */
function work(string $workId): ?array
{
    static $cache = [];
    if (array_key_exists($workId, $cache)) {
        return $cache[$workId];
    }
    $dir = work_dir($workId);
    return $cache[$workId] = $dir ? json_file($dir . '/work.json') : null;
}

/** One chapter of a work, or null. */
function chapter(string $workId, string $n): ?array
{
    if (!preg_match('/^[0-9]{1,4}[a-z]?$/i', $n)) {
        return null;
    }
    $dir = work_dir($workId);
    return $dir ? json_file($dir . '/c/' . $n . '.json') : null;
}

/** The chapter before and after this one, for the reader's footer. */
function neighbours(array $meta, string $n): array
{
    $list = array_column($meta['chapters'] ?? [], 'n');
    $i = array_search($n, $list, true);
    if ($i === false) {
        return [null, null];
    }
    return [$list[$i - 1] ?? null, $list[$i + 1] ?? null];
}

/**
 * Other editions of the same work — the four Qur'ans, or the Hebrew
 * scriptures in their Jewish and Christian translations. Matched on title,
 * which is what makes two entries the same book in different hands.
 */
function editions_of(array $meta): array
{
    $out = [];
    foreach (catalog()['religions'] as $r) {
        foreach ($r['sections'] as $s) {
            foreach ($s['works'] as $w) {
                if ($w['id'] === $meta['id'] || !empty($w['borrowed_from'])) {
                    continue;
                }
                if (mb_strtolower($w['title']) === mb_strtolower($meta['title'])) {
                    $out[] = $w;
                }
            }
        }
    }
    return $out;
}

/** Open the search index, or null when it has not been built. */
function search_db(): ?PDO
{
    static $db = false;
    if ($db !== false) {
        return $db;
    }
    if (!is_file(SEARCH_DB) || !extension_loaded('pdo_sqlite')) {
        return $db = null;
    }
    try {
        $db = new PDO('sqlite:' . SEARCH_DB, null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        $db->exec('PRAGMA query_only = 1');
    } catch (PDOException) {
        $db = null;
    }
    return $db;
}

/**
 * Turn what someone typed into an FTS5 query.
 *
 * FTS5's own syntax uses ", *, NEAR, AND and so on, and a stray quote is a
 * syntax error rather than a search. Words are extracted and re-quoted, so
 * anything at all can be typed safely; a "phrase in quotes" is kept as one.
 */
function fts_query(string $q): string
{
    $terms = [];
    if (preg_match_all('/"([^"]+)"/u', $q, $m)) {
        foreach ($m[1] as $phrase) {
            $words = preg_split('/[^\p{L}\p{N}]+/u', $phrase, -1, PREG_SPLIT_NO_EMPTY);
            if ($words) {
                $terms[] = '"' . implode(' ', $words) . '"';
            }
        }
        $q = preg_replace('/"[^"]+"/u', ' ', $q);
    }
    foreach (preg_split('/[^\p{L}\p{N}\*]+/u', $q, -1, PREG_SPLIT_NO_EMPTY) as $w) {
        $star = str_ends_with($w, '*');
        $w = trim($w, '*');
        if ($w === '') {
            continue;
        }
        $terms[] = '"' . $w . '"' . ($star ? '*' : '');
    }
    return implode(' ', $terms);
}

/** Escape for HTML. */
function e(?string $s): string
{
    return htmlspecialchars((string) $s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

/** A URL within the app. */
function u(string $page, array $params = []): string
{
    return $params ? $page . '?' . http_build_query($params) : $page;
}

function religion_name(string $id): string
{
    return ['judaism' => 'Judaism', 'christianity' => 'Christianity',
            'islam' => 'Islam'][$id] ?? $id;
}

/** How a work was modernized, in words. */
function tier_label(?string $tier): string
{
    return match ($tier) {
        'full' => 'Modernized in full',
        'safe' => 'Lightly modernized',
        'none' => 'As received',
        default => 'Modernized',
    };
}

function num(int|float|null $n): string
{
    return number_format((float) ($n ?? 0));
}
